routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
	Route::get('/home', 'HomeController@index')->name('home');

	Route::namespace('Master')->group(function () {
		Route::get('permit_categories', 'PermitCategoryController@index')->name('permit_categories.index');

		Route::get('educations', 'EducationController@showEducations');
		Route::get('provinces', 'IndonesiaController@showProvinces');
		Route::get('provinces/{id}/cities', 'IndonesiaController@showCities');
		Route::get('cities/{id}/districts', 'IndonesiaController@showDistricts');
		Route::get('districts/{id}/villages', 'IndonesiaController@showVillages');
		Route::resource('roles', 'RoleController');

		Route::get('curriculums/datatable', 'CurriculumController@datatable')->name('curriculums.datatable');
		Route::get('curriculums/{id}/add/{grade_id}', 'CurriculumDetailController@create')->name('curriculums.details.add');
		Route::put('curriculums/{id}/store/{grade_id}', 'CurriculumDetailController@store')->name('curriculums.details.store');
		Route::put('curriculums/{id}/update/{grade_id}', 'CurriculumDetailController@update')->name('curriculums.details.update');
		Route::put('curriculums/{id}/delete/{grade_id}', 'CurriculumDetailController@destroy')->name('curriculums.details.destroy');
		Route::resource('curriculums', 'CurriculumController');

		Route::get('classes/active', 'ClassController@getActive')->name('classes.active');
		Route::get('classes/datatable', 'ClassController@datatable')->name('classes.datatable');
		Route::resource('classes', 'ClassController');

		Route::get('extracurriculars/datatable', 'ExtraCurricularController@datatable')->name('extracurriculars.datatable');
		Route::resource('extracurriculars', 'ExtraCurricularController');

		Route::get('lesson_categories/datatable', 'LessonCategoryController@datatable')->name('lesson_categories.datatable');
		Route::resource('lesson_categories', 'LessonCategoryController');
		Route::get('lessons/datatable', 'LessonController@datatable')->name('lessons.datatable');
		Route::resource('lessons', 'LessonController');

		Route::get('school_times/datatable', 'SchoolTimeController@datatable')->name('school_times.datatable');
		Route::resource('school_times', 'SchoolTimeController');
		Route::get('students/hasclass', 'StudentController@hasClasses')->name('students.hasclass');
		Route::get('students/hasclass/none/datatable', 'StudentController@doesntHaveClassesDatatable')->name('students.hasclass.none.datatable');
		Route::get('students/datatable', 'StudentController@datatable')->name('students.datatable');
		Route::resource('students', 'StudentController');
		Route::get('employees/datatable', 'EmployeeController@datatable')->name('employees.datatable');
		Route::resource('employees', 'EmployeeController');

		Route::get('school_years/{id}/classes', 'SchoolYearController@getClasses')->name('school_years.classes');
		Route::get('school_years', 'SchoolYearController@index')->name('school_years.index');

		Route::get('teachers/datatable', 'TeacherController@datatable')->name('teachers.datatable');
		Route::resource('teachers', 'TeacherController');
		Route::get('users/datatable', 'UserController@datatable')->name('users.datatable');
		Route::resource('users', 'UserController');
	});

	Route::namespace('Classes')->group(function () {
		Route::get('attendances', 'StudentAttendanceController@index')->name('attendances.index');
		Route::get('attendances/show', 'StudentAttendanceController@show')->name('attendances.show');
		Route::post('attendances/update', 'StudentAttendanceController@update')->name('attendances.update');

		Route::get('lesson_journals', 'LessonJournalController@index')->name('lesson_journals.index');
		Route::get('lesson_journals/show', 'LessonJournalController@show')->name('lesson_journals.show');
		Route::post('lesson_journals/update', 'LessonJournalController@update')->name('lesson_journals.update');

		Route::get('student_permits/datatable', 'StudentPermitController@datatable')->name('student_permits.datatable');
		Route::resource('student_permits', 'StudentPermitController');

		Route::get('class_guardians', 'ClassGuardianController@index')->name('classes.guardians.index');
		Route::get('class_guardians/{id}/edit', 'ClassGuardianController@edit')->name('classes.guardians.edit');
		Route::put('class_guardians/{id}/update', 'ClassGuardianController@update')->name('classes.guardians.update');
		Route::get('class_students', 'ClassStudentController@index')->name('classes.students.index');
		Route::get('class_students/datatable', 'ClassStudentController@datatable')->name('classes.students.datatable');
		Route::get('class_students/{id}/students', 'ClassStudentController@show')->name('classes.students.show');
		Route::get('class_students/{id}/students/datatable', 'ClassStudentController@show_datatable')->name('classes.students.show.datatable');
		Route::get('class_students/{id}/add', 'ClassStudentController@add')->name('classes.students.add');
		Route::put('class_students/{id}/store', 'ClassStudentController@store')->name('classes.students.store');
		Route::put('class_students/{id}/remove', 'ClassStudentController@destroy')->name('classes.students.destroy');
	});

	Route::namespace('Calendar')->group(function () {
		Route::get('calendar_academic', 'CalendarController@index')->name('calendar.index');
		Route::get('calendar_academic/setting', 'CalendarController@edit')->name('calendar.edit');
		Route::post('calendar_academic/setting', 'CalendarController@update')->name('calendar.update');

		Route::get('events/school_year/active', 'EventController@getOnActiveSchoolYear')->name('events.show.school_year.active')->middleware('calendar.set');
		Route::get('events/datatable', 'EventController@datatable')->name('events.datatable')->middleware('calendar.set');
		Route::get('events/upcoming', 'EventController@getUpcoming')->name('events.upcoming');
		Route::resource('events', 'EventController')->middleware('calendar.set');

		Route::get('lesson_schedules/datatable', 'LessonScheduleController@datatable')->name('lesson_schedules.datatable');
		Route::get('lesson_schedules/{id}/schedules', 'LessonScheduleController@show')->name('lesson_schedules.show');
		Route::get('lesson_schedules/{id}/schedules/create', 'LessonScheduleController@create')->name('lesson_schedules.add');
		Route::post('lesson_schedules/{id}/schedules/store', 'LessonScheduleController@store')->name('lesson_schedules.store');
		Route::get('lesson_schedules/{id}', 'LessonScheduleController@edit')->name('lesson_schedules.edit');
		Route::patch('lesson_schedules/{id}', 'LessonScheduleController@update')->name('lesson_schedules.update');
		Route::delete('lesson_schedules/{id}', 'LessonScheduleController@destroy')->name('lesson_schedules.delete');
		Route::get('lesson_schedules', 'LessonScheduleController@index')->name('lesson_schedules.index');
	});

	Route::prefix('reports')->group(function () {
		Route::get('students', 'Report\ReportStudentController@index')->name('reports.students');
		Route::get('students/datatable', 'Report\ReportStudentController@datatable')->name('reports.students.datatable');
		Route::get('students/export/pdf', 'Report\ReportStudentController@exportPdf')->name('reports.students.export.pdf');
		Route::get('students/export/xls', 'Report\ReportStudentController@exportExcel')->name('reports.students.export.xls');
		Route::get('students/show', 'Report\ReportStudentController@show')->name('reports.students.show');
		Route::get('class_students', 'Report\ReportClassStudentController@index')->name('reports.class_students');
		Route::get('class_students/show', 'Report\ReportClassStudentController@show')->name('reports.class_students.show');
		Route::get('student_attendances/class', 'Report\StudentAttendance\ReportClassController@index')->name('reports.student_attendances.class');
		Route::get('student_attendances/class/show', 'Report\StudentAttendance\ReportClassController@show')->name('reports.student_attendances.class.show');

		Route::prefix('stats')->group(function () {
			Route::get('employees', 'Report\ReportStudentController@index')->name('reports.stats.students');
			Route::get('students', 'Report\ReportStudentController@index')->name('reports.stats.students');
		});
	});

	Route::prefix('stats')->group(function () {
		Route::prefix('employee')->group(function () {
			Route::get('religions', 'Stat\EmployeeController@getReligions')->name('stats.employee.religions');
		});
		Route::prefix('student')->group(function () {
			Route::get('religions', 'Stat\StudentController@getReligions')->name('stats.student.religions');
		});
	});

	Route::prefix('settings')->group(function () {
		Route::prefix('general')->group(function () {
			Route::get('/', 'Setting\SettingController@index')->name('settings.index');
			Route::put('/', 'Setting\SettingController@update')->name('settings.update');
		});
	});
});

app/Models/Master/BloodType.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class BloodType.
 *
 * @package namespace App\Models;
 */
class BloodType extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name'];

    public function students()
    {
        return $this->hasMany('App\Models\Master\Student');
    }
}

app/Models/Master/Classes.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Classes extends Model implements Transformable
{
    use TransformableTrait;

    protected $table = 'classes';

    protected $fillable = [
        'name', 'grade_id', 'school_year_id', 'active'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = ucwords($value);
    }

    public function grade()
    {
        return $this->belongsTo('App\Models\Master\Grade', 'grade_id');
    }

    public function students()
    {
        return $this->belongsToMany('App\Models\Master\Student', 'class_students', 'class_id', 'student_id')->withTimestamps();
    }

    public function guardian()
    {
        return $this->belongsToMany('App\Models\Master\Employee', 'class_guardians', 'class_id', 'employee_id')->withTimestamps();
    }

    public function lesson_schedules()
    {
        return $this->hasMany('App\Models\LessonSchedule', 'class_id');
    }

    public function lessons()
    {
        return $this->belongsToMany('App\Models\Master\Lesson', 'lesson_schedules', 'class_id', 'lesson_id');
    }

    public function teachers()
    {
        return $this->belongsToMany('App\Models\Master\Teacher', 'lesson_schedules', 'class_id', 'teacher_id');
    }

    public function school_years()
    {
        return $this->belongsToMany('App\Models\Master\SchoolYear', 'class_students', 'class_id', 'school_year_id');
    }
}

app/Models/Master/Curriculum.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Curriculum extends Model implements Transformable
{
    use TransformableTrait;
    
    protected $table = 'curriculums';

    protected $fillable = [
        'name'
    ];

    public function lessons()
    {
        return $this->belongsToMany('App\Models\Master\Lesson', 'curriculum_details', 'curriculum_id', 'lesson_id');
    }
}

app/Models/Master/DayWeek.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class DayWeek.
 *
 * @package namespace App\Models;
 */
class DayWeek extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'day_weeks';

    public function holiday()
    {
        return $this->hasOne('App\Models\SchoolYearHoliday', 'day_week_id');
    }
}

app/Models/Master/Education.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Education.
 *
 * @package namespace App\Models;
 */
class Education extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'educations';

}

app/Models/Master/Employee.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Employee.
 *
 * @package namespace App\Models;
 */
class Employee extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'employees';

    protected $fillable = [
        'nip', 'nik', 'name', 'sex', 'birth_place', 'birth_date', 'address', 'village_id', 'zip_code', 'religion_id', 'registered_at', 'image_path', 'active', 'phone'
    ];

    protected $dates = [
        'birth_date',
        'registered_at',
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = ucwords($value);
    }

    public function setBirthPlaceAttribute($value)
    {
        $this->attributes['birth_place'] = ucwords($value);
    }

    public function religion()
    {
        return $this->belongsTo('App\Models\Master\Religion', 'religion_id');
    }

    public function village()
    {
        return $this->belongsTo('App\Models\Master\Village', 'village_id');
    }

    public function teacher()
    {
        return $this->hasOne('App\Models\Master\Teacher', 'employee_id');
    }

    public function employee_educations()
    {
        return $this->hasMany('App\Models\Master\EmployeeEducation', 'employee_id');
    }

}

app/Models/Master/EmployeeEducation.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class EmployeeEducation.
 *
 * @package namespace App\Models;
 */
class EmployeeEducation extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'employee_educations';

    protected $fillable = [
        'employee_id', 'education_id', 'place', 'department', 'year_start', 'year_end', 'certificate_number', 'gpa'
    ];

    public function employee()
    {
        return $this->belongsTo('App\Models\Master\Employee', 'employee_id');
    }

    public function education()
    {
        return $this->belongsTo('App\Models\Master\Education', 'education_id');
    }

}

app/Models/Master/EventCategory.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class EventCategory.
 *
 * @package namespace App\Models;
 */
class EventCategory extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'event_categories';

}

app/Models/Master/ExtraCurricular.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class ExtraCurricular.
 *
 * @package namespace App\Models;
 */
class ExtraCurricular extends Model implements Transformable
{
    use TransformableTrait;

    protected $table = 'extracurriculars';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'coach', 'event_time', 'description', 'active'];


    public function students()
    {
        return $this->belongsToMany('App\Models\Master\Student', 'extracurricular_students', 'extracurricular_id', 'student_id')->withTimestamps();
    }
}

app/Models/Master/Grade.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Grade.
 *
 * @package namespace App\Models;
 */
class Grade extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];

    public function lessons()
    {
        return $this->belongsToMany('App\Models\Master\Lesson', 'curriculum_details', 'grade_id', 'lesson_id')->withPivot('allocation', 'kkm')->withTimestamps();
    }

    public function classes()
    {
        return $this->hasMany('App\Models\Master\Classes', 'grade_id');
    }
}

app/Models/Master/Semester.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class Semester extends Model
{
    //
}

resources/views/modules/master/user/create.blade.php
@extends('templates.data.tabler.app')

@section('title')
Tambah User
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('user create') }}
@endsection

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
            <div class="card-status bg-blue"></div>
			<div class="card-body">
				<div class="row">
                    <div class="col-md-12">
                        <form action="{{ route('users.store') }}" method="POST" class="form-horizontal" role="form">
                            @csrf
                            <div class="form-group row @if ($errors->has('name')) has-error @endif">
                                <label class="form-label col-md-2">Nama</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="name" placeholder="Nama Lengkap" required>
                                    @if ($errors->has('name')) <div class="invalid-feedback">{{ $errors->first('name') }}</div> @endif
                                </div>
                            </div>
                            <div class="form-group row @if ($errors->has('email')) has-error @endif">
                                <label class="form-label col-md-2">E-mail</label>
                                <div class="col-md-6">
                                    <input type="email" class="form-control" name="email" placeholder="Alamat E-mail" required>
                                    @if ($errors->has('email')) <div class="invalid-feedback">{{ $errors->first('email') }}</div> @endif
                                </div>
                            </div>
                            <div class="form-group row @if ($errors->has('role_name')) has-error @endif">
                                <label class="form-label col-md-2">Type User</label>
                                <div class="col-md-3">
                                    <select class="form-control" name="role_name">
                                        <option value="">Pilih Type...</option>
                                        @foreach ($roles as $role)
                                        <option value="{{ $role->name }}">{{ $role->description }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('role_name')) <div class="invalid-feedback">{{ $errors->first('role_name') }}</div> @endif
                                </div>
                            </div>
                            <div class="form-group row @if ($errors->has('password')) has-error @endif">
                                <label class="form-label col-md-2">Password</label>
                                <div class="col-md-4">
                                    <input type="password" class="form-control" name="password" placeholder="Password min. 6 karakter" required>
                                    @if ($errors->has('password')) <div class="invalid-feedback">{{ $errors->first('password') }}</div> @endif
                                </div>
                            </div>
                            <div class="form-group row @if ($errors->has('password_confirmation')) has-error @endif">
                                <label class="form-label col-md-2">Konfirmasi Password</label>
                                <div class="col-md-4">
                                    <input type="password" class="form-control" name="password_confirmation" placeholder="Password min. 6 karakter" required>
                                    @if ($errors->has('password_confirmation')) <div class="invalid-feedback">{{ $errors->first('password_confirmation') }}</div> @endif
                                </div>
                            </div>
                            <hr>
                            <div class="form-group row">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
                                    <a href="{{ url()->previous() }}" class="btn btn-default"><i class="fa fa-times-circle"></i> Batal</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/modules/master/user/edit.blade.php
@extends('templates.data.tabler.app')

@section('title')
Edit User
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('user edit', $user) }}
@endsection

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
            <div class="card-status bg-blue"></div>
			<div class="card-body">
				<div class="row">
                    <div class="col-md-12">
                        <form action="{{ route('users.update', $user->id) }}" method="POST" class="form-horizontal" role="form">
                            @csrf
                            @method('PUT')
                            <div class="form-group row @if ($errors->has('name')) has-error @endif">
                                <label class="form-label col-md-2">Nama</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="name" placeholder="Nama Lengkap" value="{{ $user->name }}" required>
                                    @if ($errors->has('name')) <div class="invalid-feedback">{{ $errors->first('name') }}</div> @endif
                                </div>
                            </div>
                            <div class="form-group row @if ($errors->has('email')) has-error @endif">
                                <label class="form-label col-md-2">E-mail</label>
                                <div class="col-md-6">
                                    <input type="email" class="form-control" name="email" placeholder="Alamat E-mail" value="{{ $user->email }}" required>
                                    @if ($errors->has('email')) <div class="invalid-feedback">{{ $errors->first('email') }}</div> @endif
                                </div>
                            </div>
                            <hr>
                            <div class="form-group row">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
                                    <a href="{{ url()->previous() }}" class="btn btn-default"><i class="fa fa-times-circle"></i> Batal</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/modules/master/user/view.blade.php
@extends('templates.data.tabler.app')

@section('title')
User
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('user') }}
@endsection

@section('content')
<div class="row" id="baseapp">
	<div class="col-md-12">
		<div class="card">
			<div class="card-status bg-blue"></div>
			<div class="card-header">
				<div class="card-options">
					<a href="{{ route('users.create') }}" class="btn btn-primary" dusk="link-user-create"><i class="fa fa-plus-circle"></i> Tambah</a>
				</div>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col-md-12">
						<table id="table" class="table table-hovered table-striped" width="100%">
							<thead class="thead-light">
								<tr>
									<th class="text-center">Nama</th>
									<th class="text-center">E-mail</th>
									<th class="text-center">Jenis User</th>
									<th class="text-center">Dibuat</th>
									<th class="text-center">Diupdate</th>
									<th class="text-center"></th>
								</tr>
							</thead>
							<tbody></tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('scripts')
<script>
var vm = new Vue({
	el: '#baseapp',
	data: {
		table: null,
	},
	methods: {
		initDatatable: function () {
		    this.table = $('#table').DataTable({
		        processing: true,
		        serverSide: true,
		        responsive: true,
		        ajax: '{{ route('users.datatable') }}',
		        columns: [
		            { data: 'name', name: 'name' },
		            { data: 'email', name: 'email' },
		            { data: 'roles', name: 'roles', className: 'text-center', sortable: false, searchable: false },
		            { data: 'created_at', name: 'created_at', className: 'text-center' },
		            { data: 'updated_at', name: 'updated_at', className: 'text-center' },
		            { data: 'action', name: 'action', className: 'text-center', sortable: false, searchable: false }
		        ],
		        language: { 
			       "processing": "<span class='text text-info'><b><i class='fa fa-spinner fa-spin'></i> Loading...</b></span>"
			    }
		    });
		}
	},
	mounted(){
		this.initDatatable();
	}
})
</script>
@endsection